### ISSUE TITLE
啥时候能升级下laravel框架到最新，目前5.2太老了

### ISSUE THREAD

**Issue by easin** [lxerxa/actionview#114]
啥时候能升级下laravel框架到最新，目前5.2太老了，很多好的插件没有用上

**Comment by lxerxa** [comment]
很期待您的pull request.

**Comment by git9am** [comment]
We come across this project and think it worthy to get it up-to-date, it's not easy though.

Here are some critical challenges and possible solutions as we're working on the update:

- code styles

  Before huge refactoring/updating, it's good to have a consistent code style so that we won't mess up details and concentrate on the high level. Here's a preflight PR for this https://github.com/lxerxa/actionview/pull/127

- jenssegers/laravel-mongodb

  Note that laravel-mongodb is having breaking changes in a [future release](https://github.com/jenssegers/laravel-mongodb/projects). And so far, before version 4 is released, Laravel 6 is the latest level it supports. (See https://github.com/jenssegers/laravel-mongodb#laravel-version-compatibility) This means we'll easily move forward to Laravel 6 first.

- chumper/zipper

  This package is no longer maintained (https://github.com/Chumper/Zipper#note) and we should seek for an alternative. Hopefully [madnest/madzipper](https://github.com/madnest/madzipper) is a good candidate.

- framework level update

  The [official document](https://laravel.com/docs/6.x/upgrade#upgrade-6.0) has a checklist for this. But it seems jumping from 5.2 to 6.x is not easy because there are many minor version between them. A feasible plan is as follow:

  - create a brand new Laravel 6 project;
  - list all newly added files to the Laravel 5.2, which can be simply copied to the new project:
     `git diff --name-only --diff-filter=A 56585752121d8fb60106536f7d169e9d4b2b4415..8871f9a9d918c601ef7e997ea648bfc775666814`
  - list all modification except for creating:
     `git diff --diff-filter=CDMRTUXB 56585752121d8fb60106536f7d169e9d4b2b4415..8871f9a9d918c601ef7e997ea648bfc775666814`
     We checked this are no more than 1k lines, so it's not pretty hard to port to the newer version.

**Comment by easin** [comment]
so difficult

**Comment by lyhiving** [comment]
> 很期待您的pull request.

已更新PR
